name: dy_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.21+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.3+1
  hive: ^2.2.3
  http: ^0.13.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  connectivity:
  data_connection_checker_nulls: ^0.0.2
  flutter_easyloading:
  flutter_launcher_icons: ^0.10.0
  provider: ^6.0.3
  intl: ^0.17.0
  search_choices: ^2.1.4
  flutter_barcode_scanner: ^2.0.0
  blue_thermal_printer: ^1.2.3
  dropdown_search: ^5.0.3
  dropdown_plus: ^0.0.9
  printing: ^5.9.3
  shared_preferences:
  date_format: ^2.0.7
  quantity_input: ^1.0.2
  animated_widgets: ^1.1.0
  url_launcher: ^6.1.11
dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_name: ^0.0.1
flutter_launcher_name:
  name: "WarraqDy"
flutter_icons:
  image_path: "assets/images/full_logo.png"
  android: true
  min_sdk_android: 21
  ios: true
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/new/
    - assets/images/customer_logo/

  fonts:
    - family: GE SS Two
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-ExtraLight.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
        - asset: assets/fonts/arial.ttf